Add help function

diff --git a/scripts/.local/bin/fpk b/scripts/.local/bin/fpk
--- a/scripts/.local/bin/fpk
+++ b/scripts/.local/bin/fpk
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# Wrapper functions for better flatpak management with fzf
+# Flatpak management wrapper with fzf integration
 #
 set -euo pipefail
 
@@ -12,8 +12,27 @@ for dependency in "${dependencies[@]}"; do
   fi
 done
 
-#Query
+#Global variables
 readonly QUERY="${2:-}"
+
+show_help() {
+    cat << EOF
+Usage: $(basename "$0") [OPTION] [QUERY]
+Flatpak management wrapper with fzf integration
+
+OPTIONS:
+    -s  Search for packages
+    -i  Install package
+    -l  List installed packages
+    -r  Remove package
+    -u  Update all packages
+    -h  Show this help
+
+EXAMPLES:
+    $(basename "$0") -s firefox
+    $(basename "$0") -i
+EOF
+}
 
 flatpak_picker(){
   local application query
@@ -23,7 +42,7 @@ flatpak_picker(){
   elif [[ "$#" -eq 0 ]]; then
     application=$(fzf --delimiter='\t' --with-nth=1,2)
   else
-    echo "ERROR: flatpak_picker can have more than 1 argument"
+    echo "ERROR: flatpak_picker can't have more than 1 argument"
   fi
   app_id=$(echo "$application" | awk -F '\t' '{print $3}')
   echo "$app_id"
@@ -72,6 +91,7 @@ while getopts "silru" flag; do
       flatpak update
       ;;
     ?)
-      echo "ERROR: $1 isn't a valid option"
+      show_help
+      exit 1
   esac
 done
