add lock file and change default picker

diff --git a/scripts/drun b/scripts/drun
--- a/scripts/drun
+++ b/scripts/drun
@@ -4,63 +4,73 @@ set -euo pipefail
 
 system_dir="/usr/share/applications"
 local_dir="$HOME/.local/share/applications"
+lock_dir="${XDG_STATE_HOME:-$HOME/.local/state}/drun"
+lock="${lock_dir}/drun.lock"
+
+trap 'rm -fv "${lock}"' ERR
+
+mkdir -pv "${lock_dir}"
+[[ -f "${lock_dir}/drun.lock" ]] && exit
+touch "${lock}"
 
 declare -A desktop_files
 
 parse_desktop_file() {
-  local file=$1
-  local regex=$2
-  mapfile -t -n 1000 lines <"${file}"
+	local file=$1
+	local regex=$2
+	mapfile -t -n 1000 lines <"${file}"
 
-  block=0
-  for line in "${lines[@]}"; do
+	block=0
+	for line in "${lines[@]}"; do
 
-    if [[ block -eq 0 ]]; then
-      if [[ "${line}" == '[Desktop Entry]' ]]; then
-        block=1
-      fi
-    elif [[ block -eq 1 ]]; then
-      if [[ "${line}" =~ ^\[.*\]$ ]]; then
-        return
-      elif [[ "${line}" =~ $regex ]]; then
-        echo "${line#*=}"
-        return
-      fi
-    fi
-  done
+		if [[ block -eq 0 ]]; then
+			if [[ "${line}" == '[Desktop Entry]' ]]; then
+				block=1
+			fi
+		elif [[ block -eq 1 ]]; then
+			if [[ "${line}" =~ ^\[.*\]$ ]]; then
+				return
+			elif [[ "${line}" =~ $regex ]]; then
+				echo "${line#*=}"
+				return
+			fi
+		fi
+	done
 
-  return
+	return
 }
 
 for file in "${system_dir}"/* "${local_dir}"/*; do
-  if [[ "${file}" =~ .+\.desktop$ ]]; then
-    app_name=$(parse_desktop_file "${file}" '^Name=.+')
-    echo "${app_name}" >&2
-    if [[ -n "${app_name}" ]]; then
-      desktop_files["${app_name}"]="${file}"
-    fi
-  fi
+	if [[ "${file}" =~ .+\.desktop$ ]]; then
+		app_name=$(parse_desktop_file "${file}" '^Name=.+')
+		echo "${app_name}" >&2
+		if [[ -n "${app_name}" ]]; then
+			desktop_files["${app_name}"]="${file}"
+		fi
+	fi
 done
 
-app_name=$(printf '%s\n' "${!desktop_files[@]}" | sort | uniq | wmenu "$@")
+app_name=$(printf '%s\n' "${!desktop_files[@]}" | sort | uniq | fzf-menu "$@")
 
 if [[ -z "${app_name}" ]]; then
-  exit 0
+	exit 0
 fi
 
 if [[ -z "${desktop_files[${app_name}]}" ]]; then
-  echo "Failed to retrieved desktop file for ${desktop_files[${app_name}]}" >&2
-  exit 1
+	echo "Failed to retrieved desktop file for ${desktop_files[${app_name}]}" >&2
+	exit 1
 fi
 
 app_file="${desktop_files[${app_name}]}"
 app_file=$(realpath "$app_file")
 
 if [[ $(parse_desktop_file "${app_file}" '^Terminal=true$') == true ]]; then
-  cmd=$(parse_desktop_file "${app_file}" '^Exec=.+')
-  #leave cmd expansion unquoted to allow globbing and word splitting of parameters
-  #shellcheck disable=SC2086
-  xdg-terminal-exec ${cmd#*=}
+	cmd=$(parse_desktop_file "${app_file}" '^Exec=.+')
+	#leave cmd expansion unquoted to allow globbing and word splitting of parameters
+	#shellcheck disable=SC2086
+	xdg-terminal-exec ${cmd#*=} &
 else
-  dex "${app_file}"
+	dex "${app_file}" &
 fi
+
+rm -fv "${lock}"
